import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import NavBar from '@/components/NavBar'
import SideBar from '@/components/SideBar'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-neutral w-screen h-screen overflow-x-hidden'>
        <NavBar/>
        <SideBar/>
        <Hero/>
      </main>
    </>
  )
}
